version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
    - postgres
    ports:
    - 5050:80
    ## you can change pgAdmin default username/password with below environment variables
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
  graphql-engine:
    image: hasura/graphql-engine:v1.2.2
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: secret
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "HS256", "key": "secretsecretsecretsecretsecretsecret"}'
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: 'anonymous'
      NETWORK_MEMBERSHIP_INVITATION_WEBHOOK_URL: 'http://host.docker.internal:3000/api/webhooks/network-membership-invitation'
      VERIFICATION_CODE_WEBHOOK_URL: 'http://host.docker.internal:3000/api/webhooks/verification-code'
      USER_WEBHOOK_URL: 'http://host.docker.internal:3000/api/webhooks/user'
      NETWORK_USER_WEBHOOK_URL: 'http://host.docker.internal:3000/api/webhooks/network-user'
      NETWORK_USER_RELATIONSHIP_WEBHOOK_URL: 'http://host.docker.internal:3000/api/webhooks/network-user-relationship'
      COMMENT_WEBHOOK_URL: 'http://host.docker.internal:3000/api/webhooks/comment'
      CONTENT_STAR_WEBHOOK_URL: 'http://host.docker.internal:3000/api/webhooks/content-star'
      CONTENT_WEBHOOK_URL: 'http://host.docker.internal:3000/api/webhooks/content'
      MEDIA_WEBHOOK_URL: 'http://host.docker.internal:3000/api/webhooks/media'
volumes:
  db_data:
