export const NETWORK_ADMIN_ROLE = 'NETWORK_ADMIN';
export const COMMUNITY_MANAGER_ROLE = 'COMMUNITY_MANAGER';
export const MEMBER_ROLE = 'MEMBER';

export const PENDING_NETWORK_USER_RELATIONSHIP_TYPE = 'PENDING';
export const CONNECTED_NETWORK_USER_RELATIONSHIP_TYPE = 'CONNECTED';
export const DECLINED_NETWORK_USER_RELATIONSHIP_TYPE = 'DECLINED';
export const BLOCKED_NETWORK_USER_RELATIONSHIP_TYPE = 'BLOCKED';
export const MUTED_NETWORK_USER_RELATIONSHIP_TYPE = 'MUTED';

export const SUPER_ADMIN_VIEW_CONTEXT = '**SUPER_ADMIN_VIEW_CONTEXT**';

export const NETWORK_ACCESS_REQUEST_COUNT_USERS_OPTIONS = [
  {
    label: '0 - 100',
    value: '(0,100)',
  },
  {
    label: '100 - 500',
    value: '(100,500)',
  },
  {
    label: '500 - 2,000',
    value: '(500,2000)',
  },
  {
    label: '2,000 - 5,000',
    value: '(2000,5000)',
  },
  {
    label: '5,000 - 10,000',
    value: '(2000,10000)',
  },
  {
    label: '10,000+',
    value: '(10000,)',
  },
];

export const BASE_CONTENT_TEMPLATE_TYPE = 'BASE_CONTENT_TEMPLATE_TYPE';
export const POLL_CONTENT_TEMPLATE_TYPE = 'POLL_CONTENT_TEMPLATE_TYPE';
export const AVAILABILITY_LISTING_CONTENT_TEMPLATE_TYPE = 'AVAILABILITY_LISTING_CONTENT_TEMPLATE_TYPE';
export const OPPORTUNITY_LISTING_CONTENT_TEMPLATE_TYPE = 'OPPORTUNITY_LISTING_CONTENT_TEMPLATE_TYPE';
export const EVENT_CONTENT_TEMPLATE_TYPE = 'EVENT_CONTENT_TEMPLATE_TYPE';
export const SESSION_CONTENT_TEMPLATE_TYPE = 'SESSION_CONTENT_TEMPLATE_TYPE';
