export const NETWORK_ADMIN_ROLE = 'NETWORK_ADMIN';
export const COMMUNITY_MANAGER_ROLE = 'COMMUNITY_MANAGER_ROLE';
export const MEMBER_ROLE = 'MEMBER_ROLE';

export const SUPER_ADMIN_VIEW_CONTEXT = '**SUPER_ADMIN_VIEW_CONTEXT**';
